[package]
name = "hello-google-oauth2"
version = "0.1.0"
edition = "2024"

[dependencies]
google-drive3 = "6.0.0"
serde = "1.0.219"
serde_json = "1.0.140"
tokio = { version = "1.45.0", features = ["full"] }
